stages:
  preprocess:
    cmd: uv run python -m src.preprocess
    deps:
      - data/ieee_cis.parquet
      - src/preprocess.py
      - configs/params.yaml
    params:
      - configs/params.yaml:
          - dataset
          - preprocess
    outs:
      - data/processed/train.csv
      - data/processed/test.csv
    metrics:
      - data/processed/stats.json:
          cache: false

  train:
    cmd: uv run python -m src.train
    deps:
      - data/processed/train.csv
      - src/train.py
      - src/features.py
    params:
      - configs/params.yaml:
          - dataset
          - train
    outs:
      - models/classifier.pkl
      - models/run_id.txt

  evaluate:
    cmd: uv run python -m src.evaluate
    deps:
      - data/processed/test.csv
      - models/classifier.pkl
      - models/run_id.txt
      - src/evaluate.py
      - src/features.py
    params:
      - configs/params.yaml:
          - dataset
          - train
          - evaluate
    metrics:
      - metrics.json:
          cache: false
