stages:
  preprocess:
    cmd: uv run python src/preprocess.py
    deps:
      - data/churn_data.csv
      - src/preprocess.py
    params:
      - configs/params.yaml:
          - preprocess
    outs:
      - data/processed/train.csv
      - data/processed/test.csv
    metrics:
      - data/processed/stats.json:
          cache: false

  train:
    cmd: uv run python src/train.py
    deps:
      - data/processed/train.csv
      - src/train.py
    params:
      - configs/params.yaml:
          - train
    outs:
      - models/churn_model.pkl

  evaluate:
    cmd: uv run python src/evaluate.py
    deps:
      - data/processed/test.csv
      - models/churn_model.pkl
      - src/evaluate.py
    params:
      - configs/params.yaml:
          - evaluate
    metrics:
      - metrics.json:
          cache: false
