apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: churn-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/my-neme-eh-jeff/customer_churn_CICD.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: churn-serving
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
