apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inference-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/my-neme-eh-jeff/ML-deployment-system-for-autoresearch.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: inference
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
