"""Open a GitHub-App-signed PR that bumps the inference-api image SHA in k8s/deployment.yaml.

Called by the CI workflow after a successful inference-api image build, when
`paths-filter` says api-affecting code (`src/api.py`, `Dockerfile`,
`pyproject.toml`, or `uv.lock`) changed on the just-pushed commit.

We deliberately go through a PR (rather than a direct push) because main is
protected by a classic branch rule requiring `lint-and-test` + `compile-kfp`
status checks to have passed on every landing commit. A direct push with
`[skip ci]` skips those checks and gets rejected with GH006. The PR path:

  1. PR triggers a fresh CI run on its head commit (lint-and-test + compile-kfp).
  2. Required checks pass.
  3. Auto-merge fires.
  4. Squash merge lands on main with a clean linear history.
  5. ArgoCD reconciles k8s/deployment.yaml and rolls inference-api pods.

This is the SAME signed-commit / auto-merge machinery the autoresearch loop
uses for its per-iter PRs. We just narrow the scope here: only the `image:`
line in deployment.yaml is touched. The autoresearch path mutates params,
src, history, and the `mlops/classifier-version` annotation — they don't
collide.

Env contract (provided by the workflow):
  IMAGE_SHA               full 40-char commit SHA tagged on the new image
  GH_OWNER                e.g. `my-neme-eh-jeff`
  GH_REPO                 e.g. `ML-deployment-system-for-autoresearch`
  GH_APP_ID               GitHub App id
  GH_INSTALLATION_ID      installation id for this repo
  GH_PEM_SECRET_PROJECT   GCP project hosting the PEM secret
  GH_PEM_SECRET_NAME      Secret Manager secret name (e.g. `github-app-key`)

IAM: the CI service account (`churn-cicd@…`) needs
`roles/secretmanager.secretAccessor` on `GH_PEM_SECRET_NAME`. Grant once via:

    gcloud secrets add-iam-policy-binding github-app-key \\
        --member=serviceAccount:churn-cicd@$PROJECT.iam.gserviceaccount.com \\
        --role=roles/secretmanager.secretAccessor

The autoresearch-sa K8s SA already has this binding for its own runs; this
just adds the CI WIF principal.
"""

from __future__ import annotations

import os
import re
import sys

from auto_experiment import github_commit


def _bump_image_line(content: str, new_sha: str) -> tuple[str, bool]:
    """Replace the inference-api `image:` SHA with new_sha. Return (new, changed)."""
    pattern = re.compile(
        r"(image:\s*ghcr\.io/[^/\s]+/inference-api:)([0-9a-fA-F]{7,40})"
    )
    match = pattern.search(content)
    if not match:
        sys.exit(
            "ERROR: couldn't find an `image: ghcr.io/.../inference-api:<sha>` line "
            "in k8s/deployment.yaml. Schema must have changed; update this script."
        )
    if match.group(2) == new_sha:
        return content, False
    return pattern.sub(rf"\g<1>{new_sha}", content), True


def _require_env(name: str) -> str:
    val = os.environ.get(name)
    if not val:
        sys.exit(f"ERROR: required env {name!r} is not set.")
    return val


def main() -> int:
    image_sha = _require_env("IMAGE_SHA")
    owner = _require_env("GH_OWNER")
    repo = _require_env("GH_REPO")
    app_id = _require_env("GH_APP_ID")
    installation_id = _require_env("GH_INSTALLATION_ID")
    project = _require_env("GH_PEM_SECRET_PROJECT")
    secret = _require_env("GH_PEM_SECRET_NAME")

    short = image_sha[:7]

    token = github_commit.get_installation_token(
        app_id, installation_id, project, secret
    )

    # Read current deployment.yaml off main, mutate only the image line,
    # short-circuit if the SHA is already correct (avoids no-op PR spam if
    # somebody manually pushed the same SHA between build and bump).
    current, _file_sha = github_commit.fetch_file_from_main(
        token, owner, repo, "k8s/deployment.yaml"
    )
    new_content, changed = _bump_image_line(current, image_sha)
    if not changed:
        print(f"k8s/deployment.yaml already pinned to {short} — no PR needed.")
        return 0

    branch = f"ci/image-bump-{short}"
    print(f"creating branch {branch} off main HEAD...")
    github_commit.create_branch_from_main(token, owner, repo, branch)

    title = f"ci: bump inference-api image to {short}"
    body = (
        f"Auto-generated by `.github/workflows/ci.yaml` after a successful "
        f"inference-api docker build.\n\n"
        f"Pins `k8s/deployment.yaml` to `inference-api:{image_sha}` "
        f"so ArgoCD reconciles the new build onto the cluster.\n\n"
        f"Auto-merge enabled. Required checks (`lint-and-test`, `compile-kfp`) "
        f"will run on this PR and the merge fires when they go green."
    )

    sha = github_commit.commit_files_to_branch(
        token,
        owner,
        repo,
        branch,
        title,
        [("k8s/deployment.yaml", new_content.encode("utf-8"))],
    )
    print(f"committed {sha[:8]} on {branch}")

    pr_url, _ = github_commit.open_pull_request(
        token, owner, repo, branch, title, body, auto_merge=True
    )
    print(f"opened PR with auto-merge: {pr_url}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
